version: '3.8'
services:
  api-desjardin-bank:
    container_name: api-desjardin-bank
    build:
        context: ./
        dockerfile: Dockerfile
    image: api-desjardin-bank:latest
    ports:
        - 8080:8080
    environment:
          - POSTGRESQL_URL=db
          - POSTGRESQL_PORT=5432
          - POSTGRESQL_DATABASE=postgres
          - POSTGRESQL_USER=postgres
          - POSTGRESQL_PASSWORD=postgres
    networks:
        - spring-cloud-network
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
        - spring-cloud-network
volumes:
  postgres-data:
networks:
    spring-cloud-network:
        driver: bridge
